### ISSUE TITLE
Debian only?

### ISSUE THREAD

**Issue by nekr0z** [qu1x/huawei-wmi#1]
Up until and including 7f66556 this repo could be cloned and used on any distro, even LFS (providing it had `systemd`, `udev` and usual GNU utils). Now `sudo make install` would fail on anything but Debian. Are you planning to support other distros (I'm not talking packages here, but at least the way it was in 7f66556)?

**Comment by n3vu0r** [comment]
Oops, I will restore the Makefile and put the Debian package into a subdirectory with some symlinks to the root directory. Other distros should be supported as well.

**Comment by n3vu0r** [comment]
it's back ;)

**Comment by nekr0z** [comment]
> it's back ;)

Great! You kinda scared me with that debian all-in. ;)
