### ISSUE TITLE
systemd complains "Special user nobody configured, this is not safe!"

### ISSUE THREAD

**Issue by kopperp** [qu1x/huawei-wmi#12]
systemd states in [[1]](https://github.com/systemd/systemd/blob/bed0b7dfc0070e920d00c89d9a4fd4db8d974cf0/catalog/systemd.catalog.in#L468):

> This is not safe. The @OFFENDING_USER@ user's main purpose on Linux-based operating systems is to be the owner of files that otherwise cannot be mapped to any local user. It's used by the NFS client and Linux user namespacing, among others. By running a unit's processes under the identity of this user they might possibly get read and even write access to such files that cannot otherwise be mapped.
> 
> It is strongly recommended to avoid running services under this user identity, in particular on systems using NFS or running containers. Allocate a user ID specific to this service, either statically via systemd-sysusers or dynamically via the DynamicUser= service setting.

Thus, the line `User=nobody` in [huawei-wmi-reinstate.service](https://github.com/qu1x/huawei-wmi/blob/e5273ab8d71bca47afa6c32f6e016450151c522a/generic/huawei-wmi-1.1.2/huawei-wmi-reinstate.service) should be changed to `DynamicUser=yes`. Tested the change on Arch Linux and it successfully removed the warning.

**Comment by n3vu0r** [comment]
Oh, that's good to know. I will test it on Debian Buster/Bullseye.

**Comment by n3vu0r** [comment]
Thanks! It's now part of the new release (and will probably make it into the AUR package).
