### ISSUE TITLE
Gnome Extension and permission problem

### ISSUE THREAD

**Issue by fincan** [qu1x/huawei-wmi#13]
Hi,
my system is on Archlinux 5.16 and uptodate. I installed your package from AUR and I added my user to the huawei-wmi. Finally I installed and enabled [the gnome extension.](https://extensions.gnome.org/extension/4580/huawei-wmi-controls/).
I restarted the system but from the extension panel, I cannot change the protection mode.
I checked logs and I saw that:
"JS ERROR: Gio.IOErrorEnum: Error opening file “/sys/devices/platform/huawei-wmi/charge_control_thresholds”: Permission denied
_set_bpm@/home/cihat/.local/share/gnome-shell/extensions/huawei-wmi@apps.sdore.me/extension.js:70:25
_init/<@/home/cihat/.local/share/gnome-shell/extensions/huawei-wmi@apps.sdore.me/extension.js:49:40
activate@resource:///org/gnome/shell/ui/popupMenu.js:191:14
vfunc_button_release_event@resource:///org/gnome/shell/ui/popupMenu.js:138:14"
What should I do?
Best,
Cihat.

**Comment by n3vu0r** [comment]
If this turns out to be correct, I would assume the panel extention is runnung as some system user instead of your desktop user.

**Comment by fincan** [comment]
Hi again,
I have just solved the issue. I checked install package and there are 2 systemd services. I enabled and started them and logout/login and now gnome extension works perfect.
Sorry to bother you.
