### ISSUE TITLE
HUAWEI MateBook X Pro 2022 "Unkwon key pressed, code 0x02c1"

### ISSUE THREAD

**Issue by dark-beep-boop** [qu1x/huawei-wmi#17]
I have an Arch Linux installation in a Huawei MateBook X Pro 2022 laptop and there's an annoying message that keeps spamming in the journal:

...
ene 08 17:49:16 logos kernel: input input12: Unknown key pressed, code: 0x02c1
ene 08 17:49:16 logos kernel: input input12: Unknown key pressed, code: 0x02c1
ene 08 17:49:17 logos kernel: input input12: Unknown key pressed, code: 0x02c1
...

The main problem with it is that it floods the journal and can make it difficult to use journalctl normally. 

One workaround could be to add { KE_IGNORE, 0x2c1, { KEY_RESERVED } }, to huawei-wmi.c.

[This Archlinux forum thread](https://bbs.archlinux.org/viewtopic.php?pid=2085797#p2085797) describes the issue with more detail.

**Comment by n3vu0r** [comment]
This repository is about systemd units and not the kernel driver. Please open this issue at  [aymanbagabas/Huawei-WMI](https://github.com/aymanbagabas/Huawei-WMI).

**Comment by dark-beep-boop** [comment]
Right. Sorry then.
