### ISSUE TITLE
Repository planned?

### ISSUE THREAD

**Issue by nekr0z** [qu1x/huawei-wmi#2]
Do you plan to host a repository, or do you plan publishing straight to Debian?

I've put up a [repo](http://evgenykuznetsov.org/repo/) for `matebook-applet`, hope you don't mind me including `huawei-wmi` .deb until you publish, so that dependency gets resolved?

**Comment by n3vu0r** [comment]
Ah very nice! Sure, you can and should include `huawei-wmi`.

I wanted to host an own repo, too, mainly for a custom kernel (APU2 boards) but haven't yet decided which tool to use. I'm interested in having both packages being released to Debian (never did). I guess, this requires a bit more care and maybe the kernel 5 series should be in sid first. But in the meantime I could try to get rid of the lintian complains.

**Comment by nekr0z** [comment]
Sure, it's all pointless without kernel 5.0+ (and probably even DKMS with driver version 3.0, since it didn't have all these hooks before that; or indeed wait till 3.0 is in mainline and _that_ kernel is in sid).

Just in case you were curious: I used [aptly](https://www.aptly.info/) to set up the repo. The documentation is hit-or-miss, but it's doable, and since I already had my blog hosted adding a subdirectory with repo to be served from the same hosting was just an rsync.

**Comment by n3vu0r** [comment]
Thanks for the hint, aptly it great, I would have overlooked it. Having finally a [repo](https://github.com/qu1x/huawei-wmi/tree/master/debian#repository), too.
