### ISSUE TITLE
ExecStart path is not absolute

### ISSUE THREAD

**Issue by kakobrekla** [qu1x/huawei-wmi#3]
Hi,

when installing the services (generic) on Ubuntu 18.04 we get
```
...
systemd[1]: /lib/systemd/system/huawei-wmi-reinstate.service:12: Executable path is not absolute: sh -c 'echo Old charge thresholds $(cat ${SYS}/charge_thresholds)'
systemd[1]: /lib/systemd/system/huawei-wmi-privilege.service:9: Executable path is not absolute: chgrp huawei-wmi ${SYS}/charge_thresholds ${SYS}/fn_lock_state
...
```

According to docs, `ExecStart` paths are supposed to be absolute. 

Changing those paths to absolute (eg. `/bin/sh`, among others) fixes the errors and the scripts execute successfully.

**Comment by n3vu0r** [comment]
Hi,

thanks for pointing it out! And sorry, I somehow missed the notification mail.

I will make the paths absolute. Ubuntu 18.04 has systemd 237 while Debian Buster which I'm using has systemd 241. Since systemd 239, absolute paths are no longer required, but they are still recommended:

> ```text
> CHANGES WITH 239:
> 
>         * The ExecStart= lines of unit files are no longer required to
>           reference absolute paths. If non-absolute paths are specified the
>           specified binary name is searched within the service manager's
>           built-in $PATH, which may be queried with 'systemd-path
>           search-binaries-default'. It's generally recommended to continue to
>           use absolute paths for all binaries specified in unit files.
> ```

**Comment by n3vu0r** [comment]
Done, released v1.0.1 and updated the Debian repo. Is it working for you?

**Comment by kakobrekla** [comment]
I am using `generic`, not `debian` (as it requires `debhelper`, `po-debconf`...).

**Comment by n3vu0r** [comment]
Ah no, I meant if the changes to the (generic) services are working for you, so we can close this issue?

**Comment by kakobrekla** [comment]
Looks identical to my patch, tested working.
