### ISSUE TITLE
Support for next-gen driver

### ISSUE THREAD

**Issue by nekr0z** [qu1x/huawei-wmi#4]
I've been in contact with Ayman, and he confirmed that the next version of his driver (already in development in master branch) will have `/sys/class/power_supply/BAT[x]/charge_control_[start|end]_threshold` (where x is 0 for our machines) for battery control, and `/sys/devices/platform/huawei-wmi/charge_tresholds` is going extinct for good (`fn_lock_state` is staying). I'll be updating the applet (hopefully by next weekend) to support this, and humbly suggest you look into this too.

Currently, failing to find `charge_thresholds`, the unit panics and gives up, and doesn't even change the permissions on `fn_lock_state`.

**Comment by n3vu0r** [comment]
Thanks for the update, I will look into it this week.

**Comment by nekr0z** [comment]
I have actually already implemented the support in matebook-applet. Compatibility-wise no changes on my side, the persistence thresholds still in the same file in the same format.

**Comment by n3vu0r** [comment]
Nice!

For me the new driver is not working:

```
input: Huawei WMI hotkeys as /devices/platform/huawei-wmi/input/input14
battery: extension failed to load: Huawei Battery Extension
battery: extension unregistered: Huawei Battery Extension
```

There is already a BAT1 and no BAT0. I'm using kernel `5.2.14`.

**Comment by nekr0z** [comment]
Sorry to hear that. You'd better file a bug to Ayman before his new version makes it into upstream kernel. ;-)

**Comment by n3vu0r** [comment]
Done. When changing `BAT0` to `BAT1` in his driver, it seems to work. Maybe it's enough to check with a wildcard `BAT?` in the systemd services and your applet but let's wait what Ayman can tell.

> (where x is 0 for our machines)

I'm having the AMD variant, I thought have the Intel variant, or?

**Comment by nekr0z** [comment]
Yeah, mine's an Intel machine. Anyway, let's wait for what Ayman has to say. In the worst case, after my big applet code refactoring earlier this week (which was due anyway) adding new endpoints is a piece of cake, and in case there's any demand I may even add custom endpoint command line option. Anyway, I'll be following the developments in Ayman's issue tracker.

**Comment by n3vu0r** [comment]
Since we have now two different endpoints, one as part of the general battery API and the other being Huawei specific (at least it is in a Huawei specific file path `/sys/devices/platform/huawei-wmi/`), I'm in favor of using/supporting only the Huawei specific endpoint. That means, I would only adjust file permissions in `/sys/devices/platform/huawei-wmi/` and never touch file permissions of the battery API. This would avoid conflicts with other potential tools which might assume they have exclusive control of the battery API. And for consistency, I would like to rename the default file in `/etc/default/huawei-wmi` from `charge_thresholds` to `charge_control_thresholds`. The new version of your applet would then require `huawei-wmi >= 2.0.0`. What do you think?

**Comment by nekr0z** [comment]
Yep, limiting to platform and never touching battery API looks like a very sane approach, I like it.

As for persistence endpoint renaming, I think I'll try to maintain backward compatibility, at least for now. Like: if (`charge_control_thresholds` exists) {use it} else {use `charge_thresholds`}.

By the way, what's your plan regarding backward compatibility? Would your `2.0.0` still be able to work on ver 3.2 of Ayman's driver? I'm kinda concerned a little, since Ayman hasn't even tagged the new version yet, and even if he did, we don't (yet?) package the driver, so you dropping backwards-incompatible `huawei-wmi` version in a repository would create quite an unpleasant user experience.

If I were you, I would at this point be considering two options: either
* make sure you're backwards compatible with pre-3.3 versions of the driver, or
* give in and take up the effort of packaging the driver as `huawei-wmi-dkms` (that would depend on kernel > 5.0) and make appropriate versions of it a dependency of `huawei-wmi`

**Comment by n3vu0r** [comment]
Thanks for your suggestions!

Yes, I want to be backwards-compatible and I think I found a flexible way to be backwards-compatible with the driver and your applet. Not yet pushed, but I'm playing with the wildcard `charge*_threshold` to access both the file in `/etc/default/huawei-wmi` and `/sys/devices/platform/huawei-wmi`. I've also moved the creation of the default file from the Makefile/postint to the service unit which changes file permissions. In this way, the unit can at anytime rename the default file to the one which the currently installed driver uses (backwards and forewards). And when your applet supports both default file names, there would be no need for `2.0.0` instead it can be `1.1.0`. To have more freedom, I moved the shell commands in the service units to external shell scripts in `/usr/lib/huawei-wmi`.

**Comment by nekr0z** [comment]
Lovely! Just make sure you remove whatever file is not needed so that I can rely on file existence for the applet to understand where the service expects to see updated records.

**Comment by n3vu0r** [comment]
Pushed it, but not yet tagged. I think I covered everything. The Debian package should also smoothly upgrade.

**Comment by nekr0z** [comment]
Almost the same moment I pushed (though not yet tagged/released) the verison with persistence-values file autodetection) ;-)
Let's test before tagging.

**Comment by nekr0z** [comment]
Allright, I did some testing, and indeed on my machine all your systemd voodoo seems to work as expected, picking up correctly whatever the driver has to offer, and the upgrade is seamless, too. The applet also seems to keep up to the pace of whatever is happening beneath.
From where I'm standing everything looks like we're almost ready to roll, see #5 for what I think is missing. I'll be tagging and releasing the applet after some minor polishing.

**Comment by n3vu0r** [comment]
I've merged your PR.

Sorry, we must retest it. I was unhappy with the wildcard expansions as they are done in the privilege unit which is run by root. Any user of group `huawei-wmi` can create files in the default directory and perform wildcard injections. So I rewrote the shell scripts without any wildcard and also double-quoted all variables.

**Comment by nekr0z** [comment]
> Sorry, we must retest it.

Don't be. It's a good thing you thought about it before we pushed this into package repos, and extra testing is never a bad thing.

**Comment by nekr0z** [comment]
Did more testing with current master. Yep, still seems to work as expected for all the cases I could imagine and simulate.

**Comment by n3vu0r** [comment]
Great, thanks. I'm tagging then and update the repo.
