### ISSUE TITLE
Executable bit set on service file

### ISSUE THREAD

**Issue by rien333** [qu1x/huawei-wmi#6]
`dmesg` gives me the following output: 

```
[    1.797312] systemd[1]: Configuration file /usr/lib/systemd/system/huawei-wmi-reinstate.service
 is marked executable. Please remove executable permission bits. Proceeding anyway.
```

I agree with dmesg here, and think the service file shouldn't be executable (right?)

**Comment by n3vu0r** [comment]
You're right, that wasn't intended. I've updated the Makefile. Thank you!!
